-- Seed: fixture completo FIFA World Cup 2026 (104 partidos)
-- ON CONFLICT DO NOTHING para que sea idempotente

INSERT INTO public.matches (id, phase, "group", round, date, time, t1, f1, t2, f2, status) VALUES
-- GRUPO A
(1,  'group', 'A', 'Grupo A · Fecha 1', '11 Jun', '16:00', 'México',        '🇲🇽', 'Sudáfrica',          '🇿🇦', 'open'),
(2,  'group', 'A', 'Grupo A · Fecha 1', '11 Jun', '23:00', 'Corea del Sur', '🇰🇷', 'R. Checa',           '🇨🇿', 'open'),
(3,  'group', 'A', 'Grupo A · Fecha 2', '18 Jun', '13:00', 'R. Checa',      '🇨🇿', 'Sudáfrica',          '🇿🇦', 'open'),
(4,  'group', 'A', 'Grupo A · Fecha 2', '18 Jun', '22:00', 'México',        '🇲🇽', 'Corea del Sur',      '🇰🇷', 'open'),
(5,  'group', 'A', 'Grupo A · Fecha 3', '24 Jun', '22:00', 'R. Checa',      '🇨🇿', 'México',             '🇲🇽', 'open'),
(6,  'group', 'A', 'Grupo A · Fecha 3', '24 Jun', '22:00', 'Sudáfrica',     '🇿🇦', 'Corea del Sur',      '🇰🇷', 'open'),
-- GRUPO B
(7,  'group', 'B', 'Grupo B · Fecha 1', '12 Jun', '16:00', 'Canadá',              '🇨🇦', 'Bosnia y Herzegovina', '🇧🇦', 'open'),
(8,  'group', 'B', 'Grupo B · Fecha 1', '13 Jun', '16:00', 'Qatar',               '🇶🇦', 'Suiza',                '🇨🇭', 'open'),
(9,  'group', 'B', 'Grupo B · Fecha 2', '18 Jun', '16:00', 'Suiza',               '🇨🇭', 'Bosnia y Herzegovina', '🇧🇦', 'open'),
(10, 'group', 'B', 'Grupo B · Fecha 2', '18 Jun', '19:00', 'Canadá',              '🇨🇦', 'Qatar',                '🇶🇦', 'open'),
(11, 'group', 'B', 'Grupo B · Fecha 3', '24 Jun', '16:00', 'Suiza',               '🇨🇭', 'Canadá',               '🇨🇦', 'open'),
(12, 'group', 'B', 'Grupo B · Fecha 3', '24 Jun', '16:00', 'Bosnia y Herzegovina','🇧🇦', 'Qatar',                '🇶🇦', 'open'),
-- GRUPO C
(13, 'group', 'C', 'Grupo C · Fecha 1', '13 Jun', '19:00', 'Brasil',   '🇧🇷', 'Marruecos', '🇲🇦', 'open'),
(14, 'group', 'C', 'Grupo C · Fecha 1', '13 Jun', '22:00', 'Haití',    '🇭🇹', 'Escocia',   '🏴󠁧󠁢󠁳󠁣󠁴󠁿', 'open'),
(15, 'group', 'C', 'Grupo C · Fecha 2', '19 Jun', '19:00', 'Brasil',   '🇧🇷', 'Haití',     '🇭🇹', 'open'),
(16, 'group', 'C', 'Grupo C · Fecha 2', '19 Jun', '22:00', 'Escocia',  '🏴󠁧󠁢󠁳󠁣󠁴󠁿', 'Marruecos', '🇲🇦', 'open'),
(17, 'group', 'C', 'Grupo C · Fecha 3', '24 Jun', '19:00', 'Escocia',  '🏴󠁧󠁢󠁳󠁣󠁴󠁿', 'Brasil',    '🇧🇷', 'open'),
(18, 'group', 'C', 'Grupo C · Fecha 3', '24 Jun', '19:00', 'Marruecos','🇲🇦', 'Haití',     '🇭🇹', 'open'),
-- GRUPO D
(19, 'group', 'D', 'Grupo D · Fecha 1', '12 Jun', '22:00', 'Estados Unidos', '🇺🇸', 'Paraguay',  '🇵🇾', 'open'),
(20, 'group', 'D', 'Grupo D · Fecha 1', '14 Jun', '01:00', 'Australia',      '🇦🇺', 'Turquía',   '🇹🇷', 'open'),
(21, 'group', 'D', 'Grupo D · Fecha 2', '19 Jun', '16:00', 'Turquía',        '🇹🇷', 'Paraguay',  '🇵🇾', 'open'),
(22, 'group', 'D', 'Grupo D · Fecha 2', '19 Jun', '01:00', 'Estados Unidos', '🇺🇸', 'Australia', '🇦🇺', 'open'),
(23, 'group', 'D', 'Grupo D · Fecha 3', '25 Jun', '23:00', 'Turquía',        '🇹🇷', 'Estados Unidos', '🇺🇸', 'open'),
(24, 'group', 'D', 'Grupo D · Fecha 3', '25 Jun', '23:00', 'Paraguay',       '🇵🇾', 'Australia', '🇦🇺', 'open'),
-- GRUPO E
(25, 'group', 'E', 'Grupo E · Fecha 1', '14 Jun', '14:00', 'Alemania',        '🇩🇪', 'Curazao',         '🇨🇼', 'open'),
(26, 'group', 'E', 'Grupo E · Fecha 1', '14 Jun', '20:00', 'Costa de Marfil', '🇨🇮', 'Ecuador',         '🇪🇨', 'open'),
(27, 'group', 'E', 'Grupo E · Fecha 2', '20 Jun', '17:00', 'Alemania',        '🇩🇪', 'Costa de Marfil', '🇨🇮', 'open'),
(28, 'group', 'E', 'Grupo E · Fecha 2', '20 Jun', '21:00', 'Curazao',         '🇨🇼', 'Ecuador',         '🇪🇨', 'open'),
(29, 'group', 'E', 'Grupo E · Fecha 3', '25 Jun', '17:00', 'Ecuador',         '🇪🇨', 'Alemania',        '🇩🇪', 'open'),
(30, 'group', 'E', 'Grupo E · Fecha 3', '25 Jun', '17:00', 'Curazao',         '🇨🇼', 'Costa de Marfil', '🇨🇮', 'open'),
-- GRUPO F
(31, 'group', 'F', 'Grupo F · Fecha 1', '14 Jun', '17:00', 'Países Bajos', '🇳🇱', 'Japón',   '🇯🇵', 'open'),
(32, 'group', 'F', 'Grupo F · Fecha 1', '14 Jun', '23:00', 'Suecia',       '🇸🇪', 'Túnez',   '🇹🇳', 'open'),
(33, 'group', 'F', 'Grupo F · Fecha 2', '20 Jun', '14:00', 'Países Bajos', '🇳🇱', 'Suecia',  '🇸🇪', 'open'),
(34, 'group', 'F', 'Grupo F · Fecha 2', '20 Jun', '01:00', 'Japón',        '🇯🇵', 'Túnez',   '🇹🇳', 'open'),
(35, 'group', 'F', 'Grupo F · Fecha 3', '25 Jun', '20:00', 'Túnez',        '🇹🇳', 'Países Bajos', '🇳🇱', 'open'),
(36, 'group', 'F', 'Grupo F · Fecha 3', '25 Jun', '20:00', 'Japón',        '🇯🇵', 'Suecia',  '🇸🇪', 'open'),
-- GRUPO G
(37, 'group', 'G', 'Grupo G · Fecha 1', '15 Jun', '16:00', 'Bélgica',      '🇧🇪', 'Egipto',        '🇪🇬', 'open'),
(38, 'group', 'G', 'Grupo G · Fecha 1', '15 Jun', '22:00', 'Irán',         '🇮🇷', 'Nueva Zelanda', '🇳🇿', 'open'),
(39, 'group', 'G', 'Grupo G · Fecha 2', '21 Jun', '16:00', 'Bélgica',      '🇧🇪', 'Irán',          '🇮🇷', 'open'),
(40, 'group', 'G', 'Grupo G · Fecha 2', '21 Jun', '22:00', 'Egipto',       '🇪🇬', 'Nueva Zelanda', '🇳🇿', 'open'),
(41, 'group', 'G', 'Grupo G · Fecha 3', '26 Jun', '00:00', 'Nueva Zelanda','🇳🇿', 'Bélgica',       '🇧🇪', 'open'),
(42, 'group', 'G', 'Grupo G · Fecha 3', '26 Jun', '00:00', 'Egipto',       '🇪🇬', 'Irán',          '🇮🇷', 'open'),
-- GRUPO H
(43, 'group', 'H', 'Grupo H · Fecha 1', '15 Jun', '13:00', 'España',        '🇪🇸', 'Cabo Verde',     '🇨🇻', 'open'),
(44, 'group', 'H', 'Grupo H · Fecha 1', '15 Jun', '19:00', 'Arabia Saudita','🇸🇦', 'Uruguay',        '🇺🇾', 'open'),
(45, 'group', 'H', 'Grupo H · Fecha 2', '21 Jun', '13:00', 'España',        '🇪🇸', 'Arabia Saudita', '🇸🇦', 'open'),
(46, 'group', 'H', 'Grupo H · Fecha 2', '21 Jun', '19:00', 'Cabo Verde',    '🇨🇻', 'Uruguay',        '🇺🇾', 'open'),
(47, 'group', 'H', 'Grupo H · Fecha 3', '26 Jun', '21:00', 'Uruguay',       '🇺🇾', 'España',         '🇪🇸', 'open'),
(48, 'group', 'H', 'Grupo H · Fecha 3', '26 Jun', '21:00', 'Cabo Verde',    '🇨🇻', 'Arabia Saudita', '🇸🇦', 'open'),
-- GRUPO I
(49, 'group', 'I', 'Grupo I · Fecha 1', '16 Jun', '16:00', 'Francia',  '🇫🇷', 'Senegal', '🇸🇳', 'open'),
(50, 'group', 'I', 'Grupo I · Fecha 1', '16 Jun', '19:00', 'Irak',     '🇮🇶', 'Noruega', '🇳🇴', 'open'),
(51, 'group', 'I', 'Grupo I · Fecha 2', '22 Jun', '18:00', 'Francia',  '🇫🇷', 'Irak',    '🇮🇶', 'open'),
(52, 'group', 'I', 'Grupo I · Fecha 2', '22 Jun', '21:00', 'Noruega',  '🇳🇴', 'Senegal', '🇸🇳', 'open'),
(53, 'group', 'I', 'Grupo I · Fecha 3', '26 Jun', '16:00', 'Noruega',  '🇳🇴', 'Francia', '🇫🇷', 'open'),
(54, 'group', 'I', 'Grupo I · Fecha 3', '26 Jun', '16:00', 'Senegal',  '🇸🇳', 'Irak',    '🇮🇶', 'open'),
-- GRUPO J
(55, 'group', 'J', 'Grupo J · Fecha 1', '16 Jun', '22:00', 'Argentina', '🇦🇷', 'Argelia',  '🇩🇿', 'open'),
(56, 'group', 'J', 'Grupo J · Fecha 1', '16 Jun', '01:00', 'Austria',   '🇦🇹', 'Jordania', '🇯🇴', 'open'),
(57, 'group', 'J', 'Grupo J · Fecha 2', '22 Jun', '14:00', 'Argentina', '🇦🇷', 'Austria',  '🇦🇹', 'open'),
(58, 'group', 'J', 'Grupo J · Fecha 2', '22 Jun', '00:00', 'Jordania',  '🇯🇴', 'Argelia',  '🇩🇿', 'open'),
(59, 'group', 'J', 'Grupo J · Fecha 3', '27 Jun', '23:00', 'Jordania',  '🇯🇴', 'Argentina','🇦🇷', 'open'),
(60, 'group', 'J', 'Grupo J · Fecha 3', '27 Jun', '23:00', 'Argelia',   '🇩🇿', 'Austria',  '🇦🇹', 'open'),
-- GRUPO K
(61, 'group', 'K', 'Grupo K · Fecha 1', '17 Jun', '14:00', 'Portugal',   '🇵🇹', 'RD Congo',  '🇨🇩', 'open'),
(62, 'group', 'K', 'Grupo K · Fecha 1', '17 Jun', '23:00', 'Uzbekistán', '🇺🇿', 'Colombia',  '🇨🇴', 'open'),
(63, 'group', 'K', 'Grupo K · Fecha 2', '23 Jun', '14:00', 'Portugal',   '🇵🇹', 'Uzbekistán','🇺🇿', 'open'),
(64, 'group', 'K', 'Grupo K · Fecha 2', '23 Jun', '23:00', 'RD Congo',   '🇨🇩', 'Colombia',  '🇨🇴', 'open'),
(65, 'group', 'K', 'Grupo K · Fecha 3', '27 Jun', '20:30', 'Colombia',   '🇨🇴', 'Portugal',  '🇵🇹', 'open'),
(66, 'group', 'K', 'Grupo K · Fecha 3', '27 Jun', '20:30', 'RD Congo',   '🇨🇩', 'Uzbekistán','🇺🇿', 'open'),
-- GRUPO L
(67, 'group', 'L', 'Grupo L · Fecha 1', '17 Jun', '17:00', 'Inglaterra', '🏴󠁧󠁢󠁥󠁮󠁧󠁿', 'Croacia',  '🇭🇷', 'open'),
(68, 'group', 'L', 'Grupo L · Fecha 1', '17 Jun', '20:00', 'Ghana',      '🇬🇭', 'Panamá',   '🇵🇦', 'open'),
(69, 'group', 'L', 'Grupo L · Fecha 2', '23 Jun', '17:00', 'Inglaterra', '🏴󠁧󠁢󠁥󠁮󠁧󠁿', 'Ghana',    '🇬🇭', 'open'),
(70, 'group', 'L', 'Grupo L · Fecha 2', '23 Jun', '20:00', 'Croacia',    '🇭🇷', 'Panamá',   '🇵🇦', 'open'),
(71, 'group', 'L', 'Grupo L · Fecha 3', '27 Jun', '18:00', 'Panamá',     '🇵🇦', 'Inglaterra','🏴󠁧󠁢󠁥󠁮󠁧󠁿', 'open'),
(72, 'group', 'L', 'Grupo L · Fecha 3', '27 Jun', '18:00', 'Croacia',    '🇭🇷', 'Ghana',    '🇬🇭', 'open'),
-- ELIMINATORIAS (equipos por definir)
(73,  'r32',   null, 'Octavos de final', '04 Jul', '18:00', 'Por definir', '🏳️', 'Por definir', '🏳️', 'locked'),
(74,  'r32',   null, 'Octavos de final', '04 Jul', '22:00', 'Por definir', '🏳️', 'Por definir', '🏳️', 'locked'),
(75,  'r32',   null, 'Octavos de final', '05 Jul', '16:00', 'Por definir', '🏳️', 'Por definir', '🏳️', 'locked'),
(76,  'r32',   null, 'Octavos de final', '05 Jul', '20:00', 'Por definir', '🏳️', 'Por definir', '🏳️', 'locked'),
(77,  'r32',   null, 'Octavos de final', '05 Jul', '23:00', 'Por definir', '🏳️', 'Por definir', '🏳️', 'locked'),
(78,  'r32',   null, 'Octavos de final', '06 Jul', '18:00', 'Por definir', '🏳️', 'Por definir', '🏳️', 'locked'),
(79,  'r32',   null, 'Octavos de final', '06 Jul', '22:00', 'Por definir', '🏳️', 'Por definir', '🏳️', 'locked'),
(80,  'r32',   null, 'Octavos de final', '06 Jul', '22:00', 'Por definir', '🏳️', 'Por definir', '🏳️', 'locked'),
(81,  'r32',   null, 'Octavos de final', '07 Jul', '18:00', 'Por definir', '🏳️', 'Por definir', '🏳️', 'locked'),
(82,  'r32',   null, 'Octavos de final', '07 Jul', '22:00', 'Por definir', '🏳️', 'Por definir', '🏳️', 'locked'),
(83,  'r32',   null, 'Octavos de final', '08 Jul', '18:00', 'Por definir', '🏳️', 'Por definir', '🏳️', 'locked'),
(84,  'r32',   null, 'Octavos de final', '08 Jul', '22:00', 'Por definir', '🏳️', 'Por definir', '🏳️', 'locked'),
(85,  'r32',   null, 'Octavos de final', '08 Jul', '22:00', 'Por definir', '🏳️', 'Por definir', '🏳️', 'locked'),
(86,  'r32',   null, 'Octavos de final', '09 Jul', '18:00', 'Por definir', '🏳️', 'Por definir', '🏳️', 'locked'),
(87,  'r32',   null, 'Octavos de final', '09 Jul', '22:00', 'Por definir', '🏳️', 'Por definir', '🏳️', 'locked'),
(88,  'r32',   null, 'Octavos de final', '09 Jul', '22:00', 'Por definir', '🏳️', 'Por definir', '🏳️', 'locked'),
(89,  'r16',   null, 'Ronda de 16',      '11 Jul', '18:00', 'Por definir', '🏳️', 'Por definir', '🏳️', 'locked'),
(90,  'r16',   null, 'Ronda de 16',      '11 Jul', '22:00', 'Por definir', '🏳️', 'Por definir', '🏳️', 'locked'),
(91,  'r16',   null, 'Ronda de 16',      '12 Jul', '18:00', 'Por definir', '🏳️', 'Por definir', '🏳️', 'locked'),
(92,  'r16',   null, 'Ronda de 16',      '12 Jul', '22:00', 'Por definir', '🏳️', 'Por definir', '🏳️', 'locked'),
(93,  'r16',   null, 'Ronda de 16',      '13 Jul', '18:00', 'Por definir', '🏳️', 'Por definir', '🏳️', 'locked'),
(94,  'r16',   null, 'Ronda de 16',      '13 Jul', '22:00', 'Por definir', '🏳️', 'Por definir', '🏳️', 'locked'),
(95,  'r16',   null, 'Ronda de 16',      '14 Jul', '18:00', 'Por definir', '🏳️', 'Por definir', '🏳️', 'locked'),
(96,  'r16',   null, 'Ronda de 16',      '14 Jul', '22:00', 'Por definir', '🏳️', 'Por definir', '🏳️', 'locked'),
(97,  'qf',    null, 'Cuartos de final', '17 Jul', '18:00', 'Por definir', '🏳️', 'Por definir', '🏳️', 'locked'),
(98,  'qf',    null, 'Cuartos de final', '17 Jul', '22:00', 'Por definir', '🏳️', 'Por definir', '🏳️', 'locked'),
(99,  'qf',    null, 'Cuartos de final', '18 Jul', '18:00', 'Por definir', '🏳️', 'Por definir', '🏳️', 'locked'),
(100, 'qf',    null, 'Cuartos de final', '18 Jul', '22:00', 'Por definir', '🏳️', 'Por definir', '🏳️', 'locked'),
(101, 'sf',    null, 'Semifinal',        '22 Jul', '22:00', 'Por definir', '🏳️', 'Por definir', '🏳️', 'locked'),
(102, 'sf',    null, 'Semifinal',        '23 Jul', '22:00', 'Por definir', '🏳️', 'Por definir', '🏳️', 'locked'),
(103, '3rd',   null, 'Tercer puesto',    '25 Jul', '20:00', 'Por definir', '🏳️', 'Por definir', '🏳️', 'locked'),
(104, 'final', null, 'FINAL',            '26 Jul', '22:00', 'Por definir', '🏳️', 'Por definir', '🏳️', 'locked')
ON CONFLICT (id) DO NOTHING;

-- Resetear la secuencia para que el próximo INSERT auto-increment empiece desde 105
SELECT setval('matches_id_seq', 104);
